version: '3.8'

services:
  strapi:
    build: ./portfolio-cms
    env_file: .env
    environment:
      - NODE_ENV=production
      - DATABASE_CLIENT=sqlite
      - DATABASE_FILENAME=/data/strapi.db
      - STRAPI_TELEMETRY_DISABLED=true
    volumes:
      - ./strapi-data:/data
      - ./portfolio-cms/public/uploads:/app/public/uploads
    restart: unless-stopped

  eleventy:
    build: ./portfolio-frontend
    environment:
      - STRAPI_URL=http://strapi:1337
    volumes:
      - ./site-build:/app/_site
      - ./portfolio-cms/public/uploads:/app/public/uploads:ro
    command: ["/bin/sh", "-c", "rm -rf /app/_site/* && npm install && npm run build:webpack && npm run build:eleventy && cp -r /app/public/uploads /app/_site/ && echo 'Build finished.'"]
    depends_on:
      - strapi

  webhook:
    build: ./webhook
    env_file: .env
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - .:/workspace
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 1m30s
      timeout: 10s
      retries: 3

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./site-build:/usr/share/nginx/html:ro
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - ./nginx/certbot/conf:/etc/letsencrypt:ro
      - ./nginx/certbot/www:/var/www/certbot:ro
    depends_on:
      - eleventy
    restart: unless-stopped

  certbot:
    image: certbot/certbot
    volumes:
      - ./nginx/certbot/conf:/etc/letsencrypt
      - ./nginx/certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
